export enum actionTypes {
  CHANGE_BANNER_TOP = "recommed/CHANGE_BANNER_TOP",
  CHANGE_HOT_ROCOMMEND = "recommed/CHANGE_HOT_ROCOMMEND",
  CHANEG_UP_RANKING = "recommed/CHANEG_UP_RANKING",
  CHANEG_NEW_RANKING = "recommed/CHANEG_NEW_RANKING",
  CHANEG_ORIGIN_RANKING = "recommed/CHANEG_ORIGIN_RANKING",
  CHANGE_HOT_RANKING = "recommed/CHANEG_HOT_RANKING",
}
