enum actionTypes {
  CHANGE_CURRENT_SONG = "player/CHANGE_CURRENT_SONG",
  CHANGE_PLAY_LIST = "player/CHANGE_PLAY_LIST",
  CHANGE_CURRENT_SONG_INDEX = "player/CHANGE_CURRENT_SONG_LIST",
  CHANGE_SEQUENCE = "player/CHANGE_SEQUENCE",
  CHANGE_CURRENT_LYRIC = "player/CHANGE_CURRENT_LYRIC",
  CHANGE_SHOW_PLAYER = "player/CHANGE_SHOW_PLAYER",
}
export default actionTypes;
